# Generated by Django 4.1 on 2023-09-12 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3, message="Le nom d'utilisateur doit comporter au moins 3 caractères.")])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Veuillez saisir une adresse e-mail valide.')])),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Le prénom doit comporter au moins 2 caractères.')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Le nom de famille doit comporter au moins 2 caractères.')])),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
