name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo docker-compose up -d
          sudo docker-compose exec web python manage.py migrate

      - name: Build Docker image
        run: |
          sudo docker build -t myapp:latest .
          sudo docker tag devops_web:latest docker.io/gals3nb0y/devops_project/devops_web:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | sudo docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          sudo docker push docker.io/gals3nb0y/devops_project/devops_web:latest
